server {
    listen 80;

    server_name test.gihp4c.edu;

    root /usr/share/nginx/html;

    location = /test {
        try_files /test/index.html =404;
    }

    location /test/ {
        try_files $uri $uri/ /test/index.html;
    }
}
