apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/component: frontend
  app.kubernetes.io/name: test
  app.kubernetes.io/part-of: gihp4c

images:
- name: test
  newName: ghcr.io/herfel97/cmclasifier
  newTag: 50b6e266980351f23750d8f90db0d1e79a3674f7
