apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/component: frontend
  app.kubernetes.io/name: test
  app.kubernetes.io/part-of: gihp4c

images:
- name: test
  newName: ghcr.io/herfel97/cmclasifier
  newTag: 8072acd358e6f0f197301d5a2b55af56770beda5
