apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/component: frontend
  app.kubernetes.io/name: test
  app.kubernetes.io/part-of: gihp4c

images:
- name: test
  newName: ghcr.io/herfel97/testopenshiftups
  newTag: 6380e98c4d58a3b7cef140d8d342834ea123003b
