apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  project: gihp4c
  source:
    repoURL: https://github.com/herfel97/testOpenShiftUPS.git
    targetRevision: HEAD
    path: deploy/overlays/k3s
  destination:
    server: https://kubernetes.default.svc
    namespace: gihp4c
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
