apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testups

resources:
  - ../../base
  - ingress.yaml

images:
  - name: testups
    newName: ghcr.io/YOUR_USER/testups
    newTag: "0.0.0"
