apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gihp4c

commonAnnotations:
  gitops.herfel97/rollout-trigger: "d9bd8b922a424ce9fcace160317ed9b985a2c2af"

resources:
  - ../../base
  - ingress.yaml

images:
  - name: test
    newName: ghcr.io/herfel97/testopenshiftups
    newTag: "latest"
